#!/bin/bash

# KeyVent Deployment Script
# This script helps deploy both frontend and backend to your server

echo "🚀 KeyVent Deployment Script"
echo "=========================="

echo ""
echo "Please follow these steps to deploy your application:"
echo ""

echo "1. First, transfer your files to the server:"
echo "   scp -r /Users/admin/keyvent-website/ok/keyvent-backend root@your-server-ip:/var/www/"
echo "   scp -r /Users/admin/keyvent-website/ok/keyvent-website/build root@your-server-ip:/var/www/keyvent-frontend/"
echo ""

echo "2. SSH into your server:"
echo "   ssh root@your-server-ip"
echo ""

echo "3. Run these commands on your server:"
echo "   ==================================="
echo ""
echo "   # Update system"
echo "   sudo apt update && sudo apt upgrade -y"
echo ""
echo "   # Install Node.js"
echo "   curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
echo "   sudo apt-get install -y nodejs"
echo ""
echo "   # Install PM2"
echo "   sudo npm install -g pm2"
echo ""
echo "   # Install Nginx"
echo "   sudo apt install nginx -y"
echo ""
echo "   # Set up backend"
echo "   cd /var/www/keyvent-backend/server"
echo "   sudo npm install --production"
echo ""
echo "   # Create backend environment file"
echo "   sudo tee .env > /dev/null << 'EOF'"
echo "   PORT=5003"
echo "   MONGODB_URI=mongodb+srv://Atif:eNBGlSs7TqtNYErM@cluster0.ngecrax.mongodb.net/"
echo "   MONGODB_DATABASE=keyvent"
echo "   NODE_ENV=production"
echo "   EOF"
echo ""
echo "   # Start backend with PM2"
echo "   sudo pm2 start server.js --name \"keyvent-backend\" --env production"
echo "   sudo pm2 startup"
echo "   sudo pm2 save"
echo ""
echo "   # Configure Nginx"
echo "   sudo tee /etc/nginx/sites-available/keyvent > /dev/null << 'EOF'"
echo "   server {"
echo "       listen 80;"
echo "       server_name _;"
echo ""
echo "       # Frontend static files"
echo "       location / {"
echo "           root /var/www/keyvent-frontend/build;"
echo "           index index.html index.htm;"
echo "           try_files \$uri \$uri/ /index.html;"
echo "       }"
echo ""
echo "       # Backend API proxy"
echo "       location /api/ {"
echo "           proxy_pass http://localhost:5003/;"
echo "           proxy_http_version 1.1;"
echo "           proxy_set_header Upgrade \$http_upgrade;"
echo "           proxy_set_header Connection 'upgrade';"
echo "           proxy_set_header Host \$host;"
echo "           proxy_set_header X-Real-IP \$remote_addr;"
echo "           proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "           proxy_set_header X-Forwarded-Proto \$scheme;"
echo "           proxy_cache_bypass \$http_upgrade;"
echo "           proxy_buffering off;"
echo "       }"
echo ""
echo "       # Security headers"
echo "       add_header X-Frame-Options \"SAMEORIGIN\" always;"
echo "       add_header X-XSS-Protection \"1; mode=block\" always;"
echo "       add_header X-Content-Type-Options \"nosniff\" always;"
echo "       add_header Referrer-Policy \"no-referrer-when-downgrade\" always;"
echo "       add_header Content-Security-Policy \"default-src 'self' http: https: data: blob: 'unsafe-inline'\" always;"
echo ""
echo "       # Gzip compression"
echo "       gzip on;"
echo "       gzip_vary on;"
echo "       gzip_min_length 1024;"
echo "       gzip_proxied expired no-cache no-store private must-revalidate auth;"
echo "       gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss application/javascript;"
echo ""
echo "       # Cache static assets"
echo "       location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {"
echo "           expires 1y;"
echo "           add_header Cache-Control \"public, immutable\";"
echo "       }"
echo "   }"
echo "   EOF"
echo ""
echo "   # Enable the site"
echo "   sudo ln -sf /etc/nginx/sites-available/keyvent /etc/nginx/sites-enabled/"
echo "   sudo rm -f /etc/nginx/sites-enabled/default"
echo ""
echo "   # Test and restart Nginx"
echo "   sudo nginx -t"
echo "   sudo systemctl restart nginx"
echo "   sudo systemctl enable nginx"
echo ""
echo "4. Your application should now be accessible at http://your-server-ip/"
echo "   Backend API: http://your-server-ip:5003/api/"
echo ""
echo "For SSL setup, run:"
echo "   sudo apt install certbot python3-certbot-nginx -y"
echo "   sudo certbot --nginx -d your-domain.com"